# Set of unnecessary hashtags use to remove from tweets
unnecessary_hashtags = {
    "#fyp",
    "#viral",
    "#like4like",
    "#viralbanget",
    "#trending",
    "#fypage",
    "#foryoupage",
    "#explore",
    "#instagood",
    "#followforfollow",
    "#f4f",
    "#likeforlike",
    "#l4l",
    "#commentforcomment",
    "#instadaily",
    "#photooftheday",
    "#viralvideo",
    "#xyzbca",
    "#beritaterkini",
    "#terkini",
}

# Dictionary to normalize slang words to their correct form
slang_mapping = {
    "gimik": "gimmick",
    "emg": "memang",
    "remeh temeh": "remeh",
    "liyu": "pusing",
    "wdym": "what do you mean",
    "mangnya": "memangnya",
    "sisok": "besok",
    "lfg": "let's go",
    "gede": "besar",
    "aja": "saja",
    "kalo": "kalau",
    "yg": "yang",
    "jg": "juga",
    "klo": "kalau",
    "trs" : "terus",
    "lbh": "lebih",
    "gk": "gak",
    "lol": "laugh out loud",
    "lmao": "laugh my ass off",
    "rofl": "rolling on floor laughing",
    "lmfao": "laughing my fucking ass off",
    "roflmao": "rolling on floor laughing my ass off",
}