name: Daily Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run the main.py
        run: python3 main.py
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_REPO_KMEANS_ID: ${{ secrets.HF_REPO_KMEANS_ID }}
          HF_REPO_NER_ID: ${{ secrets.HF_REPO_NER_ID }}